site_name: APEX
site_url: http://khuck.github.io/xpress-apex
repo_url: http://github.com/khuck/xpress-apex
repo_name: GitHub
site_description: APEX - Autonomic Performance Environment for eXascale v2.3.1
site_author: Kevin Huck (khuck@cs.uoregon.edu)
copyright: (C) 2014-2021 University of Oregon, All Rights Reserved
nav:
    - Home: index.md
    - Quick Start (HPX): quickstarthpx.md
    - Quick Start (standalone): quickstart.md
    - Feature Overview: feature.md
    - Installation: install.md
    - Usage: usage.md
#    - Use Cases: usecases.md
    - Useful Environment Variables: environment.md
#    - Research Examples: examples.md
    - API Specification : spec.md
    - API Doxygen Reference : refman.md
theme: readthedocs
markdown_extensions:
    - fenced_code
    - toc:
        permalink: True
        separator: "_"

